

    //collect articles information
    var text1 = '<article id="text1"><img class="float-left img-fluid resize" src="img/rambla.jpg" alt=""><h2>Rambla de Poblanou</h2><h3>Subtitulo 1</h3><div id="texto1"><p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Laborum dolorum id nihil illo excepturi! Totam quae accusamus dignissimos quibusdam. Id, adipisci commodi. Ipsam at nesciunt quibusdam dolor distinctio, molestiae sit!</p><p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Quasi ut quos ea, incidunt nulla dignissimos saepe enim quam vero a molestias non? Laudantium molestiae ratione modi suscipit illum quos expedita? Lorem ipsum dolor sit amet consectetur adipisicing elit. Modi sapiente fugiat placeat voluptas magnam magni ullam nam veritatis quisquam minus adipisci, facilis vitae numquam et voluptate ab dolorem nihil minima! Lorem ipsum dolor sit amet, consectetur adipisicing elit. Consequatur deserunt sapiente fugiat sit nihil nulla vel eaque reprehenderit libero incidunt deleniti sed est tenetur esse cumque illo, magnam, laboriosam explicabo.</p><p>Lorem ipsum dolor sit amet consectetur, adipisicing elit. Maiores soluta, in nulla hic animi at maxime repellat doloribus nihil similique nemo? Animi dolore qui commodi debitis totam minus repellendus soluta! Lorem ipsum, dolor sit amet consectetur adipisicing elit. Et quos exercitationem modi excepturi cum, rem quisquam fugiat praesentium dolores architecto consequuntur veniam, saepe sit voluptatibus suscipit labore amet quis maiores.</p></div><div class="position"> <button class="btn btn-danger knowMore" value="texto1">Know more ...</button></div><div class="position"><button class="btn btn-danger knowLess" value="texto1">Know less ...</button></div></article>'
    var text2 = '<article id="text1"><img class="float-left img-fluid resize" src="img/subirachs.jpg" alt=""><h2>Espai Subirachs</h2><h3>Subtitulo 2</h3><div id="texto1"><p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Laborum dolorum id nihil illo excepturi! Totam quae accusamus dignissimos quibusdam. Id, adipisci commodi. Ipsam at nesciunt quibusdam dolor distinctio, molestiae sit!</p><p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Quasi ut quos ea, incidunt nulla dignissimos saepe enim quam vero a molestias non? Laudantium molestiae ratione modi suscipit illum quos expedita? Lorem ipsum dolor sit amet consectetur adipisicing elit. Modi sapiente fugiat placeat voluptas magnam magni ullam nam veritatis quisquam minus adipisci, facilis vitae numquam et voluptate ab dolorem nihil minima! Lorem ipsum dolor sit amet, consectetur adipisicing elit. Consequatur deserunt sapiente fugiat sit nihil nulla vel eaque reprehenderit libero incidunt deleniti sed est tenetur esse cumque illo, magnam, laboriosam explicabo.</p><p>Lorem ipsum dolor sit amet consectetur, adipisicing elit. Maiores soluta, in nulla hic animi at maxime repellat doloribus nihil similique nemo? Animi dolore qui commodi debitis totam minus repellendus soluta! Lorem ipsum, dolor sit amet consectetur adipisicing elit. Et quos exercitationem modi excepturi cum, rem quisquam fugiat praesentium dolores architecto consequuntur veniam, saepe sit voluptatibus suscipit labore amet quis maiores.</p></div><div class="position"> <button class="btn btn-danger knowMore" value="texto1">Know more ...</button></div><div class="position"><button class="btn btn-danger knowLess" value="texto1">Know less ...</button></div></article>'
    var text3 = '<article id="text1"><img class="float-left img-fluid resize" src="img/gandhi.jpg" alt=""><h2>Jardins de Gandhi</h2><h3>Subtitulo 3</h3><div id="texto1"><p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Laborum dolorum id nihil illo excepturi! Totam quae accusamus dignissimos quibusdam. Id, adipisci commodi. Ipsam at nesciunt quibusdam dolor distinctio, molestiae sit!</p><p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Quasi ut quos ea, incidunt nulla dignissimos saepe enim quam vero a molestias non? Laudantium molestiae ratione modi suscipit illum quos expedita? Lorem ipsum dolor sit amet consectetur adipisicing elit. Modi sapiente fugiat placeat voluptas magnam magni ullam nam veritatis quisquam minus adipisci, facilis vitae numquam et voluptate ab dolorem nihil minima! Lorem ipsum dolor sit amet, consectetur adipisicing elit. Consequatur deserunt sapiente fugiat sit nihil nulla vel eaque reprehenderit libero incidunt deleniti sed est tenetur esse cumque illo, magnam, laboriosam explicabo.</p><p>Lorem ipsum dolor sit amet consectetur, adipisicing elit. Maiores soluta, in nulla hic animi at maxime repellat doloribus nihil similique nemo? Animi dolore qui commodi debitis totam minus repellendus soluta! Lorem ipsum, dolor sit amet consectetur adipisicing elit. Et quos exercitationem modi excepturi cum, rem quisquam fugiat praesentium dolores architecto consequuntur veniam, saepe sit voluptatibus suscipit labore amet quis maiores.</p></div><div class="position"> <button class="btn btn-danger knowMore" value="texto1">Know more ...</button></div><div class="position"><button class="btn btn-danger knowLess" value="texto1">Know less ...</button></div></article>'
    var text4 = '<article id="text1"><img class="float-left img-fluid resize" src="img/parque.jpg" alt=""><h2>Parque del Poblenou</h2><h3>Subtitulo 1</h3><div id="texto1"><p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Laborum dolorum id nihil illo excepturi! Totam quae accusamus dignissimos quibusdam. Id, adipisci commodi. Ipsam at nesciunt quibusdam dolor distinctio, molestiae sit!</p><p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Quasi ut quos ea, incidunt nulla dignissimos saepe enim quam vero a molestias non? Laudantium molestiae ratione modi suscipit illum quos expedita? Lorem ipsum dolor sit amet consectetur adipisicing elit. Modi sapiente fugiat placeat voluptas magnam magni ullam nam veritatis quisquam minus adipisci, facilis vitae numquam et voluptate ab dolorem nihil minima! Lorem ipsum dolor sit amet, consectetur adipisicing elit. Consequatur deserunt sapiente fugiat sit nihil nulla vel eaque reprehenderit libero incidunt deleniti sed est tenetur esse cumque illo, magnam, laboriosam explicabo.</p><p>Lorem ipsum dolor sit amet consectetur, adipisicing elit. Maiores soluta, in nulla hic animi at maxime repellat doloribus nihil similique nemo? Animi dolore qui commodi debitis totam minus repellendus soluta! Lorem ipsum, dolor sit amet consectetur adipisicing elit. Et quos exercitationem modi excepturi cum, rem quisquam fugiat praesentium dolores architecto consequuntur veniam, saepe sit voluptatibus suscipit labore amet quis maiores.</p></div><div class="position"> <button class="btn btn-danger knowMore" value="texto1">Know more ...</button></div><div class="position"><button class="btn btn-danger knowLess" value="texto1">Know less ...</button></div></article>'
    var text5 = '<article id="text1"><img class="float-left img-fluid resize" src="img/bogatell.jpg" alt=""><h2>Playa de Bogatell</h2><h3>Subtitulo 1</h3><div id="texto1"><p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Laborum dolorum id nihil illo excepturi! Totam quae accusamus dignissimos quibusdam. Id, adipisci commodi. Ipsam at nesciunt quibusdam dolor distinctio, molestiae sit!</p><p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Quasi ut quos ea, incidunt nulla dignissimos saepe enim quam vero a molestias non? Laudantium molestiae ratione modi suscipit illum quos expedita? Lorem ipsum dolor sit amet consectetur adipisicing elit. Modi sapiente fugiat placeat voluptas magnam magni ullam nam veritatis quisquam minus adipisci, facilis vitae numquam et voluptate ab dolorem nihil minima! Lorem ipsum dolor sit amet, consectetur adipisicing elit. Consequatur deserunt sapiente fugiat sit nihil nulla vel eaque reprehenderit libero incidunt deleniti sed est tenetur esse cumque illo, magnam, laboriosam explicabo.</p><p>Lorem ipsum dolor sit amet consectetur, adipisicing elit. Maiores soluta, in nulla hic animi at maxime repellat doloribus nihil similique nemo? Animi dolore qui commodi debitis totam minus repellendus soluta! Lorem ipsum, dolor sit amet consectetur adipisicing elit. Et quos exercitationem modi excepturi cum, rem quisquam fugiat praesentium dolores architecto consequuntur veniam, saepe sit voluptatibus suscipit labore amet quis maiores.</p></div><div class="position"> <button class="btn btn-danger knowMore" value="texto1">Know more ...</button></div><div class="position"><button class="btn btn-danger knowLess" value="texto1">Know less ...</button></div></article>'
    var text6 = '<article id="text1"><img class="float-left img-fluid resize" src="img/cementerio.jpg" alt=""><h2>Cementerio de Poblanou</h2><h3>Subtitulo 1</h3><div id="texto1"><p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Laborum dolorum id nihil illo excepturi! Totam quae accusamus dignissimos quibusdam. Id, adipisci commodi. Ipsam at nesciunt quibusdam dolor distinctio, molestiae sit!</p><p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Quasi ut quos ea, incidunt nulla dignissimos saepe enim quam vero a molestias non? Laudantium molestiae ratione modi suscipit illum quos expedita? Lorem ipsum dolor sit amet consectetur adipisicing elit. Modi sapiente fugiat placeat voluptas magnam magni ullam nam veritatis quisquam minus adipisci, facilis vitae numquam et voluptate ab dolorem nihil minima! Lorem ipsum dolor sit amet, consectetur adipisicing elit. Consequatur deserunt sapiente fugiat sit nihil nulla vel eaque reprehenderit libero incidunt deleniti sed est tenetur esse cumque illo, magnam, laboriosam explicabo.</p><p>Lorem ipsum dolor sit amet consectetur, adipisicing elit. Maiores soluta, in nulla hic animi at maxime repellat doloribus nihil similique nemo? Animi dolore qui commodi debitis totam minus repellendus soluta! Lorem ipsum, dolor sit amet consectetur adipisicing elit. Et quos exercitationem modi excepturi cum, rem quisquam fugiat praesentium dolores architecto consequuntur veniam, saepe sit voluptatibus suscipit labore amet quis maiores.</p></div><div class="position"> <button class="btn btn-danger knowMore" value="texto1">Know more ...</button></div><div class="position"><button class="btn btn-danger knowLess" value="texto1">Know less ...</button></div></article>'
    var text7 = '<article id="text1"><img class="float-left img-fluid resize" src="img/beso.jpg" alt=""><h2>El Beso de la Muerte</h2><h3>Subtitulo 1</h3><div id="texto1"><p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Laborum dolorum id nihil illo excepturi! Totam quae accusamus dignissimos quibusdam. Id, adipisci commodi. Ipsam at nesciunt quibusdam dolor distinctio, molestiae sit!</p><p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Quasi ut quos ea, incidunt nulla dignissimos saepe enim quam vero a molestias non? Laudantium molestiae ratione modi suscipit illum quos expedita? Lorem ipsum dolor sit amet consectetur adipisicing elit. Modi sapiente fugiat placeat voluptas magnam magni ullam nam veritatis quisquam minus adipisci, facilis vitae numquam et voluptate ab dolorem nihil minima! Lorem ipsum dolor sit amet, consectetur adipisicing elit. Consequatur deserunt sapiente fugiat sit nihil nulla vel eaque reprehenderit libero incidunt deleniti sed est tenetur esse cumque illo, magnam, laboriosam explicabo.</p><p>Lorem ipsum dolor sit amet consectetur, adipisicing elit. Maiores soluta, in nulla hic animi at maxime repellat doloribus nihil similique nemo? Animi dolore qui commodi debitis totam minus repellendus soluta! Lorem ipsum, dolor sit amet consectetur adipisicing elit. Et quos exercitationem modi excepturi cum, rem quisquam fugiat praesentium dolores architecto consequuntur veniam, saepe sit voluptatibus suscipit labore amet quis maiores.</p></div><div class="position"> <button class="btn btn-danger knowMore" value="texto1">Know more ...</button></div><div class="position"><button class="btn btn-danger knowLess" value="texto1">Know less ...</button></div></article>'
    var text8 = '<article id="text1"><img class="float-left img-fluid resize" src="img/maria.jpg" alt=""><h2>Carrer de Marià Aguiló</h2><h3>Subtitulo 1</h3><div id="texto1"><p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Laborum dolorum id nihil illo excepturi! Totam quae accusamus dignissimos quibusdam. Id, adipisci commodi. Ipsam at nesciunt quibusdam dolor distinctio, molestiae sit!</p><p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Quasi ut quos ea, incidunt nulla dignissimos saepe enim quam vero a molestias non? Laudantium molestiae ratione modi suscipit illum quos expedita? Lorem ipsum dolor sit amet consectetur adipisicing elit. Modi sapiente fugiat placeat voluptas magnam magni ullam nam veritatis quisquam minus adipisci, facilis vitae numquam et voluptate ab dolorem nihil minima! Lorem ipsum dolor sit amet, consectetur adipisicing elit. Consequatur deserunt sapiente fugiat sit nihil nulla vel eaque reprehenderit libero incidunt deleniti sed est tenetur esse cumque illo, magnam, laboriosam explicabo.</p><p>Lorem ipsum dolor sit amet consectetur, adipisicing elit. Maiores soluta, in nulla hic animi at maxime repellat doloribus nihil similique nemo? Animi dolore qui commodi debitis totam minus repellendus soluta! Lorem ipsum, dolor sit amet consectetur adipisicing elit. Et quos exercitationem modi excepturi cum, rem quisquam fugiat praesentium dolores architecto consequuntur veniam, saepe sit voluptatibus suscipit labore amet quis maiores.</p></div><div class="position"> <button class="btn btn-danger knowMore" value="texto1">Know more ...</button></div><div class="position"><button class="btn btn-danger knowLess" value="texto1">Know less ...</button></div></article>'
    var text9 = '<article id="text1"><img class="float-left img-fluid resize" src="img/prim.jpg" alt=""><h2>Plaça de Prim</h2><h3>Subtitulo 1</h3><div id="texto1"><p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Laborum dolorum id nihil illo excepturi! Totam quae accusamus dignissimos quibusdam. Id, adipisci commodi. Ipsam at nesciunt quibusdam dolor distinctio, molestiae sit!</p><p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Quasi ut quos ea, incidunt nulla dignissimos saepe enim quam vero a molestias non? Laudantium molestiae ratione modi suscipit illum quos expedita? Lorem ipsum dolor sit amet consectetur adipisicing elit. Modi sapiente fugiat placeat voluptas magnam magni ullam nam veritatis quisquam minus adipisci, facilis vitae numquam et voluptate ab dolorem nihil minima! Lorem ipsum dolor sit amet, consectetur adipisicing elit. Consequatur deserunt sapiente fugiat sit nihil nulla vel eaque reprehenderit libero incidunt deleniti sed est tenetur esse cumque illo, magnam, laboriosam explicabo.</p><p>Lorem ipsum dolor sit amet consectetur, adipisicing elit. Maiores soluta, in nulla hic animi at maxime repellat doloribus nihil similique nemo? Animi dolore qui commodi debitis totam minus repellendus soluta! Lorem ipsum, dolor sit amet consectetur adipisicing elit. Et quos exercitationem modi excepturi cum, rem quisquam fugiat praesentium dolores architecto consequuntur veniam, saepe sit voluptatibus suscipit labore amet quis maiores.</p></div><div class="position"> <button class="btn btn-danger knowMore" value="texto1">Know more ...</button></div><div class="position"><button class="btn btn-danger knowLess" value="texto1">Know less ...</button></div></article>'

    //Create an object with the places of the map
    var places = {
        text1: text1,
        text2: text2,
        text3: text3,
        text4: text4,
        text5: text5,
        text6: text6,
        text7: text7,
        text8: text8,
        text9: text9
    }
    
    //var buttonsMap = document.querySelectorAll('.button')
    var buttonsKnow = document.querySelectorAll('.knowMore')
    var buttonsKnowLess = document.querySelectorAll('.knowLess')
    
    //create listeners for the buttons
    let buttons = document.getElementsByClassName('button')
    //iterate through the buttons
    for (let i = 0; i < buttons.length; i++) {
        buttons[i].addEventListener('click', function(){
            //get article id from button value
            let idText = this.value
            //print articles when you click on butons
           document.getElementById('showedArticle').innerHTML= '<div>'+places[idText]+'</div>'
            //focus on the article
            window.location.href = '#showedArticle';
        })
        
    }

    buttonsKnow.forEach(function(k){
        k.onclick = showAllText
    })

    buttonsKnowLess.forEach(function(l){
        l.onclick = hideText
    })

    
   


function showAllText() {
    let idText = this.value

    document.getElementById(idText).style.overflow='visible'
    document.getElementById(idText).style.height='100%'
    document.querySelector('.knowMore').style.display='none'
    document.querySelector('.knowLess').style.display='initial'

}
function hideText(){
    let idText =this.value 

    document.getElementById(idText).style.overflow='hidden'
    document.getElementById(idText).style.height='200px'
    document.querySelector('.knowMore').style.display='initial'
    document.querySelector('.knowLess').style.display='none'
}
